# Numpy for Data Science
* [Numpy](#0)
* [Arrays](#1)
* [Input/Output](#2)
* [Data Types](#3)
* [Inspecting Array](#4)
* [Numpy Help](#5)
* [Array Math](#6)
* [Copying Arrays](#7)
* [Sorting Arrays](#8)
* [Subsetting, Slicing and Indexing](#9)
* [Array Manipulation](#10)


<a id="0"></a>
## Numpy
![Title](0.png)

In [1]:
import numpy as np

<a id="1"></a>
## Arrays
![Title](1.png)

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c = np.zeros(4)
for i in range(4):
    c[i] = a[i] + 10
c

array([11., 12., 13., 14.])

In [14]:
kedi = np.ones(10)
print(kedi)
dog = np.zeros(10)
dog

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.arange(5,10,3)

array([5, 8])

In [26]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [28]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.random((5,5))

array([[0.07454573, 0.54904978, 0.16003405, 0.81593976, 0.67797104],
       [0.39841091, 0.62178616, 0.85880033, 0.94358348, 0.63954797],
       [0.87506023, 0.78167133, 0.53358004, 0.89252177, 0.11481598],
       [0.80477405, 0.85450694, 0.2732485 , 0.4181864 , 0.01702107],
       [0.44524266, 0.63259858, 0.09358092, 0.37489794, 0.17610092]])

In [31]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.13038880e-321],
       [1.02356521e-306, 1.61317855e-307, 2.67008863e-307]])

<a id="2"></a>
## Input/Output
![Title](2.png)

In [42]:
a = np.array([1,2,3,4])
np.save("array1",a)
b = np.load("array1.npy")
b

array([1, 2, 3, 4])

In [44]:
np.savetxt("array1.txt",a, delimiter = " ")
c = np.loadtxt("array1.txt")
c

array([1., 2., 3., 4.])

<a id="3"></a>
## Data Types
![Title](3.png)

In [45]:
a = np.array([1,2,3,4],dtype = np.int64)
a

array([1, 2, 3, 4], dtype=int64)

In [46]:
a = np.array([1,2,3,4],dtype = np.float32)
a

array([1., 2., 3., 4.], dtype=float32)

<a id="4"></a>
## Inspecting Array
![Title](4.png)

In [53]:
a = np.array([[1,2,3],[4,5,6]],dtype = np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [48]:
a.shape

(2, 3)

In [49]:
len(a)

2

In [50]:
a.size

6

In [51]:
a.ndim

2

In [54]:
a.dtype

dtype('float32')

In [55]:
a.dtype.name

'float32'

In [57]:
a.astype(np.int64)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

<a id="5"></a>
## Numpy Help
![Title](5.png)

In [58]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


<a id="6"></a>
## Array Math
![Title](6.png)

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [60]:
a-b

array([-4, -4, -4, -4])

In [61]:
a*b

array([ 5, 12, 21, 32])

In [62]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [63]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [64]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [65]:
a.dot(b)

70

In [71]:
np.array([0,0,0,1,1,1]) < 0.5

array([ True,  True,  True, False, False, False])

In [69]:
a < 2

array([ True, False, False, False])

In [72]:
np.array_equal(a,b)

False

In [75]:
a

array([1, 2, 3, 4])

In [74]:
a.sum()

10

In [76]:
a.min()

1

In [77]:
a.max()

4

In [83]:
np.mean(a)

2.5

In [81]:
np.median(a)

2.5

In [82]:
np.std(a)

1.118033988749895

<a id="7"></a>
## Copying Arrays
![Title](7.png)

In [90]:
a = np.array([1,2,3,4])
b = a.view()
print(b)
c = a.copy()
print(c)

[1 2 3 4]
[1 2 3 4]


In [91]:
a[0] = 100
print(b)
print(c)

[100   2   3   4]
[1 2 3 4]


<a id="8"></a>
## Sorting Arrays
![Title](8.png)

In [103]:
a = np.array([[1,2,3],[0,-4,5]])
print(a)
a.sort()
print(a)

[[ 1  2  3]
 [ 0 -4  5]]
[[ 1  2  3]
 [-4  0  5]]


In [104]:
a.sort(axis = 0)
a

array([[-4,  0,  3],
       [ 1,  2,  5]])

<a id="9"></a>
## Subsetting, Slicing and Indexing
![Title](9.png)

In [105]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a[1,0]

4

In [107]:
a[0,1:]

array([2, 3])

In [108]:
a[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [109]:
b = np.array([0,1,2,3,4])
b[::-1]

array([4, 3, 2, 1, 0])

In [111]:
filtre = b < 2
filtre

array([ True,  True, False, False, False])

In [112]:
b[filtre]

array([0, 1])

In [115]:
b = np.array([0,1,2,3,4])
b[1],b[0],b[2]

(1, 0, 2)

In [116]:
idx = [1,0,2]
b[idx]

array([1, 0, 2])

<a id="10"></a>
## Array Manipulation
![Title](10.png)

In [130]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
np.transpose(a)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [132]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [133]:
a.shape

(2, 4)

In [137]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [141]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [142]:
np.append(a,100)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100])

In [143]:
np.insert(a, 0, -100)

array([-100,    1,    2,    3,    4,    5,    6,    7,    8])

In [144]:
np.delete(a,1)

array([1, 3, 4, 5, 6, 7, 8])

In [145]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
b = np.array([-1,-2,-3])
b

array([-1, -2, -3])

In [147]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8, -1, -2, -3])

In [152]:
np.vstack((b,b))

array([[-1, -2, -3],
       [-1, -2, -3]])

In [153]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8, -1, -2, -3])

In [161]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [162]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [163]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]